# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F4HSqWy5TZVxAdldrz-w-JZkcgbMV4UI
"""

import random

def nahodne_4_mistne_cislo():
    prvni_cislice = random.randint(1, 9)
    druha_cislice = random.randint(0, 9)
    while druha_cislice == prvni_cislice:
        druha_cislice = random.randint(0, 9)

    treti_cislice = random.randint(0, 9)
    while treti_cislice == prvni_cislice or treti_cislice == druha_cislice:
        treti_cislice = random.randint(0, 9)

    ctvrta_cislice = random.randint(0, 9)
    while ctvrta_cislice == prvni_cislice or ctvrta_cislice == druha_cislice or ctvrta_cislice == treti_cislice:
        ctvrta_cislice = random.randint(0, 9)

    return f"{prvni_cislice}{druha_cislice}{treti_cislice}{ctvrta_cislice}"

def bulls_and_cows(secret, guess):
    bulls = sum(1 for i in range(4) if secret[i] == guess[i])
    cows = sum(1 for x in guess if x in secret) - bulls
    return bulls, cows

if input("Cauky mnauky, jsi ready? Chceš zahrát Bulls and Cows? (ano/ne) >:3 ").lower() == "ano":
    gen_cislo = nahodne_4_mistne_cislo()

    while True:
        pokus = input("Napiš čtyřmístné číslo: ")

        if len(pokus) != 4 or not pokus.isdigit() or len(set(pokus)) != 4 or pokus[0] == "0":
            print("Chyba: Zadej platné čtyřmístné číslo s unikátními ciframi a první číslo nesmí být 0.")
            continue

        bulls, cows = bulls_and_cows(gen_cislo, pokus)
        print(f"Bulls: {bulls}, Cows: {cows}")

        if bulls == 4:
            print("Šikulka, že jsi to zvládl!")
            break
        else:
            print("Ajajaj, zkus to znova. Máš to špatně.")
else:
    print("Tak nic no")